export interface SubProject {
  id: string;
  title: string;
  subtitle: string;
  duration: string;
  description: string[];
  technologies: string[];
}

export interface TimelineItem {
  id: string;
  title: string;
  company: string;
  location: string;
  duration: string;
  startDate: string;
  endDate: string;
  description: string[];
  technologies: string[];
  type: 'work' | 'education' | 'project';
  logo?: string;
  subProjects?: SubProject[];
}

// Udit Sharma's actual timeline data from resume
export const timelineData: TimelineItem[] = [
  {
    id: 'work-1',
    title: 'Machine Learning Engineer',
    company: 'Viant Technology',
    location: 'Irvine, CA',
    duration: 'Feb 2022 - Present',
    startDate: '2022',
    endDate: 'Present',
    description: [
      'Leading development of cutting-edge machine learning systems for programmatic advertising',
      'Leveraged OpenAI LLM models (4o-search & text-embedding-3) API to summarize advertiser URLs and generate embeddings for effective targeting',
      'Researched and engineered innovative features using Large Language Models (LLM) enhanced by Retrieval-Augmented Generation (RAG)',
      'Built robust ETL pipelines using Python+SQL for dataset generation, offline evaluation, and Looker Studio model monitoring'
    ],
    technologies: [
      'TensorFlow',
      'PyTorch',
      'OpenAI API',
      'LLM',
      'RAG',
      'GoLang',
      'Python',
      'SQL',
      'Vertex AI',
      'Looker Studio',
      'Transformers'
    ],
    type: 'work',
    subProjects: [
      {
        id: 'viant-project-1',
        title: 'CPA Phase 2 (MLP Model)',
        subtitle: 'Deep Learning for CPA Optimization',
        duration: 'Feb 2022 - Present (Part of ongoing work)',
        description: [
          'Developed and deployed a TensorFlow-based deep learning (MLP) model on Vertex AI, improving Cost Per Action (CPA) by 20% while serving over 10 million daily impressions',
          'Engineered rich features, including offline-generated Pixel URL embeddings for semantic understanding of ad landing pages',
          'Implemented advanced data strategies: exponential weights attribution and class imbalance handling for robust training',
          'Contributed to production deployment using TensorFlow Serving & gRPC, integrated with Viant\'s GoLang bidding system',
          'Established ETL pipelines (Python, SQL) and Looker Studio dashboards for daily performance monitoring'
        ],
        technologies: [
          'TensorFlow',
          'Python',
          'SQL',
          'GoLang',
          'Vertex AI',
          'GCP',
          'Deep Learning (MLP)',
          'Feature Engineering',
          'Attribution Modeling',
          'MLOps (Deployment & Monitoring)',
          'gRPC',
          'Looker Studio'
        ]
      },
      {
        id: 'viant-project-2',
        title: 'CPA Phase 3 (TGN Model - Recommendation System)',
        subtitle: 'Temporal Graph Network for User Recommendation & CPA',
        duration: 'Feb 2022 - Present (Part of ongoing work)',
        description: [
          'Proposed, designed, and implemented a novel recommendation system using a Temporal Graph Network (TGN) in PyTorch, achieving a further 2x CPA improvement',
          'Leveraged all pixel fire events (not just impression-attributed conversions) to build a holistic view of user behavior',
          'Modeled temporal dynamics by applying a Transformer encoder over weekly graph snapshot embeddings generated by a SAGEConv GNN (PyTorch Geometric)',
          'Implemented distributed training on Vertex AI (A100 GPUs) with sharded data, and resolved complex data contamination issues in HeteroData objects',
          'Operationalized recommendations via Aerospike, with real-time mapping to ad orders and dynamic frequency capping'
        ],
        technologies: [
          'PyTorch',
          'PyTorch Geometric',
          'Transformers',
          'GNNs (GraphSAGE)',
          'Python',
          'SQL',
          'Spark (PySpark)',
          'Temporal Modeling',
          'Recommendation Systems',
          'Vertex AI (A100s)',
          'Distributed Training',
          'Aerospike',
          'Negative Sampling',
          'BCEWithLogitsLoss',
          'MLOps'
        ]
      }
    ]
  },
  {
    id: 'education-1',
    title: 'Master of Science in Computer Engineering',
    company: 'Rochester Institute of Technology',
    location: 'Rochester, NY',
    duration: 'Sep 2019 - Dec 2021',
    startDate: '2019',
    endDate: '2021',
    description: [
      'Specialized in Machine Learning and Artificial Intelligence',
      'Conducted advanced research in deep learning and neural networks',
      'Completed comprehensive coursework in computer vision, NLP, and AI systems',
      'Successfully defended thesis and graduated with distinction in Computer Engineering'
    ],
    technologies: [
      'Deep Learning',
      'Computer Vision',
      'NLP',
      'PyTorch',
      'TensorFlow',
      'Research Methods',
      'Neural Networks',
      'AI Systems'
    ],
    type: 'education'
  },
  {
    id: 'work-2',
    title: 'Graduate Research Assistant',
    company: 'Rochester Institute of Technology',
    location: 'Rochester, NY',
    duration: 'Sep 2019 - Dec 2021',
    startDate: '2019',
    endDate: '2021',
    description: [
      'Bosch Project: Designed a lightweight, multi-stage neural network pipeline for edge devices using PyTorch to detect glassbreak events with exceptionally low false positive rate of 0.0003',
      'Teaching Assistant: Enhanced Deep Learning/Math courses and tutored 35+ students per class, significantly boosting learning outcomes',
      'Collaborated with industry partners on cutting-edge AI research projects',
      'Mentored undergraduate students in machine learning concepts and implementations'
    ],
    technologies: [
      'PyTorch',
      'Edge Computing',
      'Neural Networks',
      'Signal Processing',
      'Deep Learning',
      'Teaching',
      'Research'
    ],
    type: 'work'
  },
  {
    id: 'work-3',
    title: 'Software Engineer',
    company: 'Accenture Solutions Pvt. Ltd.',
    location: 'India',
    duration: 'May 2017 - June 2019',
    startDate: '2017',
    endDate: '2019',
    description: [
      'Worked as a client-facing SAP MM and ABAP consultant specializing in the Accounts Payable process',
      'Automated creation of manual payment forms based on past creation history, reducing new incidents by 75%',
      'Reduced manual effort by 40% by applying Machine Learning and automation for GR/IR reconciliation in SAP',
      'Delivered enterprise-level solutions for major clients across various industries'
    ],
    technologies: [
      'SAP MM',
      'ABAP',
      'Machine Learning',
      'Process Automation',
      'Enterprise Software',
      'Client Relations',
      'SQL'
    ],
    type: 'work'
  },
  {
    id: 'education-2',
    title: 'Bachelor of Engineering in Information Technology',
    company: 'Devi Ahilya University',
    location: 'India',
    duration: '2013 - May 2017',
    startDate: '2013',
    endDate: '2017',
    description: [
      'Strong foundation in computer science fundamentals and information technology',
      'Coursework in programming, data structures, algorithms, and software engineering',
      'Completed comprehensive projects in web development and database management',
      'Graduated with strong academic performance and technical skills'
    ],
    technologies: [
      'Java',
      'C++',
      'Database Systems',
      'Web Development',
      'Software Engineering',
      'Data Structures',
      'Algorithms'
    ],
    type: 'education'
  },
  {
    id: 'project-1',
    title: 'GourmetNet: Food Segmentation Research',
    company: 'Published Research Paper',
    location: 'Academic Research',
    duration: '2020 - 2021',
    startDate: '2020',
    endDate: '2021',
    description: [
      'Developed a novel deep learning architecture in PyTorch for semantic segmentation of food images',
      'Advanced the state of the art in food image analysis, enabling more accurate calorie and volume estimation',
      'Deployed the model via a Flask API for real-time inference and usability in research and health applications',
      'Published paper has received 21+ citations to date, demonstrating significant research impact'
    ],
    technologies: [
      'PyTorch',
      'Computer Vision',
      'Semantic Segmentation',
      'Flask',
      'Deep Learning',
      'Research',
      'Academic Writing'
    ],
    type: 'project'
  },
  {
    id: 'project-2',
    title: 'PDF Insights Extractor with Multi-modal RAG',
    company: 'AI Personal Project',
    location: 'Independent Development',
    duration: '2025',
    startDate: '2025',
    endDate: '2025',
    description: [
      'Built a standalone RAG application using Gemma-3, LangChain, and Streamlit',
      'Implemented chat-based, context-aware information retrieval from PDFs including text, tables, and images',
      'Showcased advanced unstructured data processing and user-facing AI tool development',
      'Demonstrated expertise in modern LLM and RAG technologies'
    ],
    technologies: [
      'Gemma-3',
      'LangChain',
      'Streamlit',
      'RAG',
      'Multi-modal AI',
      'PDF Processing',
      'Python'
    ],
    type: 'project'
  },
  {
    id: 'project-3',
    title: 'SQLite to Google Slides AI Agent',
    company: 'Agentic AI Project',
    location: 'Independent Development',
    duration: '2025',
    startDate: '2025',
    endDate: '2025',
    description: [
      'Developed an autonomous AI agent using Gemini-2.0-Flash to analyze SQLite data',
      'Implemented automated insight synthesis and Google Slides presentation generation via API',
      'Demonstrated cutting-edge agentic AI capabilities for business automation',
      'Showcased end-to-end automation from data analysis to presentation delivery'
    ],
    technologies: [
      'Gemini-2.0-Flash',
      'Agentic AI',
      'SQLite',
      'Google Slides API',
      'Data Analysis',
      'Automation',
      'Python'
    ],
    type: 'project'
  }
];

// Function to sort timeline items by date (most recent first)
export const getSortedTimelineData = (): TimelineItem[] => {
  return timelineData.sort((a, b) => {
    // Handle special case: 2025 projects should come before current "Present" roles
    const aYear = a.endDate === 'Present' ? 2024 : parseInt(a.endDate);
    const bYear = b.endDate === 'Present' ? 2024 : parseInt(b.endDate);
    
    // Sort by year (descending), then by startDate if years are equal
    if (bYear !== aYear) {
      return bYear - aYear;
    }
    
    // If years are equal, sort by start date (descending)
    const aStartYear = parseInt(a.startDate);
    const bStartYear = parseInt(b.startDate);
    return bStartYear - aStartYear;
  });
}; 